logging:
  level:
    com:
      glm:
        glmback: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
application:
  multitenancy:
    seed-change-log: classpath:config/liquibase/admin/seed/local.xml
