logging:
  level:
    com:
      glm:
        glmback: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
application:
  multitenancy:
    tenants:
      - id: impeccmold
        schema: impeccmold
      - id: katilys
        schema: katilys
