logging:
  level:
    com:
      glm:
        glmback: DEBUG
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
application:
  multitenancy:
    tenants:
      - id: impeccmold
        schema: impeccmold
      - id: katilys
        schema: katilys

atelier:
  resolution:
    apercus:
      cle-active: locale
      cles:
        locale: Z2xtLXByZXZpZXctbG9jYWwtZGV2ZWxvcG1lbnRfX18=
