package com.glm.glmback.atelier.domain;

public enum RaisonDuConflit {
  GESTE_AVANT_OUVERTURE,
  TRANSITION_MEME_CATEGORIE,
  CIBLE_ECHUE_AVEC_AUTRE_ACTIVITE,
  CONTRADICTION_REGULARISATION,
  CIBLE_REMPLACEE,
  CIBLE_DEJA_TERMINEE,
}
